### ISSUE TITLE
Container not found

### ISSUE THREAD

**Issue by rezadavari** [alexlvcom/RomanNumeralGenerator#1]
Hi
I just installed your project with "composer install "and ran it, I get this error:
Fatal error: Uncaught Error: Class 'RomanNumerals\Container' not found in 
 RomanNumeralGenerator\index.php:24
Do you have any ClassLoader or something like this?

Thanks a lot.

**Comment by alexlvcom** [comment]
I haven't configured composer.json correctly, will fix shortly

**Comment by alexlvcom** [comment]
@rezadavari just merged fix into master. Please update and see updated README.

**Comment by rezadavari** [comment]
It's OK and is working perfectly.
Thanks

**Comment by alexlvcom** [comment]
Np!
